#!/bin/bash

# Installing Dependencies
echo "###################################################"
echo "installing packages."
echo "###################################################"
sudo yum install wget unzip httpd -y #> /dev/null
echo

# start & Enable service
echo "###################################################"
echo "Start & Enable HTTPD services"
sudo systemctl start httpd #or you can use service httpd start
sudo systemctl enable httpd #or you can use chkconfig httpd on
echo 

#Creating temp Directory
echo "###################################################"
echo "Starting artifact Deployement"
echo "###################################################"
mkdir -p /tmp/webfiles
cd /tmp/webfiles
echo

wget https://www.tooplate.com/zip-templates/2098_health.zip #> /dev/null
# (or use this) == https://www.tooplate.com/zip-templates/2127_little_fashion.zip
# but note it you have to change unzip and cp cmd
unzip 2098_health.zip #> /dev/null
sudo cp -r 2098_health/* /var/www/html/
echo

#bounce service
echo "###################################################"
echo "Restarting httpd service"
echo "###################################################"
systemctl restart httpd
echo

#clean up
echo "###################################################"
echo "Removing Temporary files"
echo "###################################################"
rm -rf /tmp/webfiles
echo

sudo systemctl status httpd
ls /var/www/html